/**
 * Created by marco on 26.6.2016.
 */
export const AUTH_USER =  'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';



// Sensor list
export const FETCH_SENSORS = 'FETCH_SENSORS';
export const FETCH_SENSORS_SUCCESS = 'FETCH_SENSORS_SUCCESS';
export const FETCH_SENSORS_FAILURE = 'FETCH_SENSORS_FAILURE';
export const RESET_SENSORS = 'RESET_SENSORS';

// Create new sensor
export const CREATE_SENSOR = 'CREATE_SENSOR';
export const CREATE_SENSOR_SUCCESS = 'CREATE_SENSORS_SUCCESS';
export const CREATE_SENSOR_FAILURE = 'CREATE_SENSORS_FAILURE';
export const RESET_NEW_SENSOR = 'RESET_NEW_SENSOR';

// Validate sensor fields like Name, UsageToken
export const VALIDATE_SENSOR_FIELDS = 'VALIDATE_SENSOR_FIELDS';
export const VALIDATE_SENSOR_FIELDS_SUCCESS = 'VALIDATE_SENSOR_FIELDS_SUCCESS';
export const VALIDATE_SENSOR_FIELDS_FAILURE = 'VALIDATE_SENSOR_FIELDS_FAILURE';
export const RESET_SENSOR_FIELDS = 'RESET_SENSOR_FIELDS';


// Fetch sensor
export const FETCH_SENSOR = 'FETCH_SENSOR';
export const FETCH_SENSOR_SUCCESS = 'FETCH_SENSOR_SUCCESS';
export const FETCH_SENSOR_FAILURE = 'FETCH_SENSOR_FAILURE';
export const RESET_ACTIVE_SENSOR = 'RESET_ACTIVE_SENSOR';

//Delete post
export const DELETE_SENSOR = 'DELETE_SENSOR';
export const DELETE_SENSOR_SUCCESS = 'DELETE_SENSOR_SUCCESS';
export const DELETE_SENSOR_FAILURE = 'DELETE_SENSOR_FAILURE';
export const RESET_DELETED_SENSOR = 'RESET_DELETED_SENSOR';

//Markers
export const GENERATE_MARKERS = 'GENERATE_MARKERS';
